image: node:latest

before_script:
  - npm i

pages:
  stage: deploy
  script:
    - npm run gitlab
    - cp favicon.ico public/favicon.ico
    - cp sitemap.xml public/sitemap.xml
  artifacts:
    paths:
      - public
  only:
    - master
